### ISSUE TITLE
ERROR - locast2dvr.http.interface:Exception on /device.xml [GET]

### ISSUE THREAD

**Issue by SJLBoulder** [wouterdebie/locast2dvr#9]
I've got locast2dvr running successfully with IP address 127.0.0.1, but it fails when specifying the address (192.168.1.10) of the server it's running on.  
NOTE 1: locast2plex runs successfully with IP address 192.168.1.10.
NOTE 2: By the way, config.ini keyword "bind" does not seem to be recognized.  I need to specify the IP address with --bind on the command line.

2021-01-01 14:12:22 - INFO - Facilities: Using cached file: /home/steve/.locast2dvr/facilities.zip
2021-01-01 14:12:22 - INFO - Facilities: Unzipping facilities...
2021-01-01 14:12:24 - INFO - LocastService: Logging in with xxxxxxxxx@xxxxxxx
2021-01-01 14:12:24 - INFO - LocastService: Locast login successful
2021-01-01 14:12:24 - INFO - DVR: DVR(city: Denver, zip: None, dma: 751, uid: LOCAST2DVR_0, url: http://192.168.1.10:6078) created
2021-01-01 14:12:24 - INFO - Main: Using ffmpeg at /snap/bin/ffmpeg
2021-01-01 14:12:24 - INFO - LocastService: Loading stations for Denver (cache: True, time: 3600)
2021-01-01 14:12:25 - INFO - SSDPServer: Registering upnp:rootdevice (http://192.168.1.10:6078/device.xml)
2021-01-01 14:12:25 - INFO - DVR: DVR(city: Denver, zip: None, dma: 751, uid: LOCAST2DVR_0, url: http://192.168.1.10:6078) HTTP interface started
2021-01-01 14:12:25 - INFO - Main: DVRs:
2021-01-01 14:12:25 - INFO - Main:   City    Zipcode      DMA  UID           URL
2021-01-01 14:12:25 - INFO - Main:   ------  ---------  -----  ------------  ------------------------
2021-01-01 14:12:25 - INFO - Main:   Denver               751  LOCAST2DVR_0  http://192.168.1.10:6078
2021-01-01 14:12:25 - ERROR - locast2dvr.http.interface: Exception on /device.xml [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/locast2dvr-0.4.28-py3.6.egg/locast2dvr/http/interface.py", line 48, in device_xml
    host_and_port=host_and_port)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.6/dist-packages/Jinja2-3.0.0a1-py3.6.egg/jinja2/environment.py", line 885, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.6/dist-packages/Jinja2-3.0.0a1-py3.6.egg/jinja2/environment.py", line 838, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/Jinja2-3.0.0a1-py3.6.egg/jinja2/environment.py", line 812, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/Jinja2-3.0.0a1-py3.6.egg/jinja2/loaders.py", line 112, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: device.xml

**Comment by wouterdebie** [comment]
I fixed the inconsistency in the parameter naming. Things are now `bind_address` or `--bind-address`.

The unfortunate thing is that I can't seem to reproduce the stack trace you provided. It seems that in that particular case the `device.xml` template couldn't be found. Would you mind trying this with the latest version?

**Comment by SJLBoulder** [comment]
Reminder - update the usage doc with the bind-address and bind_address changes.

But, still getting the device.xml template not found:
steve@ubuntu-plex:~/Downloads/locast2dvr-0.4.35$ locast2dvr --config ./config.ini
2021-01-05 15:44:56 - INFO - CLI: locast2dvr 0.4.35 starting
2021-01-05 15:44:56 - INFO - Facilities: Using cached file: /home/steve/.locast2dvr/facilities.zip
2021-01-05 15:44:56 - INFO - Facilities: Unzipping facilities...
2021-01-05 15:44:58 - INFO - Facilities: Done loading..
2021-01-05 15:44:58 - INFO - LocastService: Logging in with xxxxxxxxx@xxxxx.xxx
2021-01-05 15:44:58 - INFO - LocastService: Locast login successful
2021-01-05 15:44:58 - INFO - LocastService: Loading stations for Denver (cache: True, cache timeout: 3600, days: 8)
2021-01-05 15:44:59 - INFO - DVR: DVR(city: Denver, zip: None, dma: 751, uid: LOCAST2DVR_0, url: http://192.168.1.10:6078) created
2021-01-05 15:44:59 - INFO - Main: Using ffmpeg at /snap/bin/ffmpeg
2021-01-05 15:44:59 - INFO - SSDPServer: Registering upnp:rootdevice (http://192.168.1.10:6078/device.xml)
2021-01-05 15:44:59 - INFO - DVR: DVR(city: Denver, zip: None, dma: 751, uid: LOCAST2DVR_0, url: http://192.168.1.10:6078) HTTP interface started
2021-01-05 15:44:59 - INFO - Main: DVRs:
2021-01-05 15:44:59 - INFO - Main:   City    Zipcode      DMA  UID           URL
2021-01-05 15:44:59 - INFO - Main:   ------  ---------  -----  ------------  ------------------------
2021-01-05 15:44:59 - INFO - Main:   Denver               751  LOCAST2DVR_0  http://192.168.1.10:6078
2021-01-05 15:45:00 - ERROR - locast2dvr.http.interface: Exception on /device.xml [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/locast2dvr-0.4.35-py3.6.egg/locast2dvr/http/interface.py", line 46, in device_xml
    host_and_port=host_and_port)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python3.6/dist-packages/Jinja2-3.0.0a1-py3.6.egg/jinja2/environment.py", line 885, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python3.6/dist-packages/Jinja2-3.0.0a1-py3.6.egg/jinja2/environment.py", line 838, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/Jinja2-3.0.0a1-py3.6.egg/jinja2/environment.py", line 812, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/Jinja2-3.0.0a1-py3.6.egg/jinja2/loaders.py", line 112, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: device.xml

**Comment by wouterdebie** [comment]
Thanks for the reminder about the README, I just updated it. 

I don't understand why device.xml can't be found when you change the bind address.. Can you see if `device.xml` exists in your python dist? (i.e. `find /usr/local/lib/python3.6/ -name 'device.xml'`)

**Comment by wouterdebie** [comment]
And would you mind sharing your `config.ini`?

**Comment by SJLBoulder** [comment]
config.ini:  NOTE: password is just alphanumeric, no special symbols
username="xxxxxxxx@xxxxxxx.xxx"
password="xxxxxxxxxxxx" 
port="6078"
verbose="0"
tuner_count="4"
bind_address="192.168.1.10"

There is no device.xml.  Exactly where should it be in /usr/local/lib/python3.6 ?

steve@ubuntu-plex:~/Downloads/locast2dvr-0.4.35$ find /usr/local/lib/python3.6/ --name 'device.xml'
find: unknown predicate `--name'
steve@ubuntu-plex:~/Downloads/locast2dvr-0.4.35$ find /usr/local/lib/python3.6/ -name 'device.xml'
steve@ubuntu-plex:~/Downloads/locast2dvr-0.4.35$

**Comment by SJLBoulder** [comment]
Looks like the tilde caused the strike-thru.

**Comment by wouterdebie** [comment]
Ah, how are you installing? The preferred method is to pip install
locast2dvr, but it seems you have downloaded the source?

**Comment by SJLBoulder** [comment]
Like I commented in another thread, I'm not a particularly knowledgeable linux user, and haven't used Linux/Unix much in the past 10 years (retired OMVS IBMer).

FIRST I TRIED:
steve@ubuntu-plex:~/Downloads$ pip install 'locast2dvr'
Command 'pip' not found, but can be installed with:
sudo apt install python-pip


NEXT:
steve@ubuntu-plex:~/Downloads$ python3 -m pip install 'locast2dvr'
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement locast2dvr
ERROR: No matching distribution found for locast2dvr

So, then I downloaded/extracted the *.tar file and then:
steve@ubuntu-plex:~/Downloads/locast2dvr-0.4.35$ ls
build  dist  locast2dvr  locast2dvr.egg-info  MANIFEST.in  PKG-INFO  README.md  setup.cfg  setup.py
steve@ubuntu-plex:~/Downloads/locast2dvr-0.4.35$ sudo python3 setup.py install
running install
running bdist_egg
... etc. until the end ...
Using /usr/local/lib/python3.6/dist-packages/MarkupSafe-2.0.0a1-py3.6-linux-x86_64.egg
Finished processing dependencies for locast2dvr==0.4.35


THEN:
steve@ubuntu-plex:~/Downloads/locast2dvr-0.4.35$ python3 -m pip install 'locast2dvr'
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: locast2dvr in /usr/local/lib/python3.6/dist-packages/locast2dvr-0.4.35-py3.6.egg (0.4.35)
Requirement already satisfied: click~=7.1.0 in /usr/local/lib/python3.6/dist-packages/click-7.1.2-py3.6.egg (from locast2dvr) (7.1.2)
Requirement already satisfied: click-config-file~=0.6.0 in /usr/local/lib/python3.6/dist-packages/click_config_file-0.6.0-py3.6.egg (from locast2dvr) (0.6.0)
Requirement already satisfied: click-option-group~=0.5.0 in /usr/local/lib/python3.6/dist-packages/click_option_group-0.5.2-py3.6.egg (from locast2dvr) (0.5.2)
Requirement already satisfied: Flask~=1.1.0 in /usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg (from locast2dvr) (1.1.2)
Requirement already satisfied: fuzzywuzzy~=0.18.0 in /usr/local/lib/python3.6/dist-packages/fuzzywuzzy-0.18.0-py3.6.egg (from locast2dvr) (0.18.0)
Requirement already satisfied: m3u8~=0.7.0 in /usr/local/lib/python3.6/dist-packages/m3u8-0.7.1-py3.6.egg (from locast2dvr) (0.7.1)
Requirement already satisfied: requests~=2.24.0 in /usr/local/lib/python3.6/dist-packages/requests-2.24.0-py3.6.egg (from locast2dvr) (2.24.0)
Requirement already satisfied: waitress~=1.4.0 in /usr/local/lib/python3.6/dist-packages/waitress-1.4.4-py3.6.egg (from locast2dvr) (1.4.4)
Requirement already satisfied: Paste~=3.5.0 in /usr/local/lib/python3.6/dist-packages/Paste-3.5.0-py3.6.egg (from locast2dvr) (3.5.0)
Requirement already satisfied: tabulate~=0.8.0 in /usr/local/lib/python3.6/dist-packages/tabulate-0.8.7-py3.6.egg (from locast2dvr) (0.8.7)
Requirement already satisfied: configobj>=5.0.6 in /usr/local/lib/python3.6/dist-packages/configobj-5.0.6-py3.6.egg (from click-config-file~=0.6.0->locast2dvr) (5.0.6)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from configobj>=5.0.6->click-config-file~=0.6.0->locast2dvr) (1.11.0)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.6/dist-packages/Jinja2-3.0.0a1-py3.6.egg (from Flask~=1.1.0->locast2dvr) (3.0.0a1)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.6/dist-packages/Werkzeug-1.0.1-py3.6.egg (from Flask~=1.1.0->locast2dvr) (1.0.1)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.6/dist-packages/itsdangerous-2.0.0a1-py3.6.egg (from Flask~=1.1.0->locast2dvr) (2.0.0a1)
Requirement already satisfied: MarkupSafe>=1.1 in /usr/local/lib/python3.6/dist-packages/MarkupSafe-2.0.0a1-py3.6-linux-x86_64.egg (from Jinja2>=2.10.1->Flask~=1.1.0->locast2dvr) (2.0.0a1)
Requirement already satisfied: iso8601 in /usr/local/lib/python3.6/dist-packages/iso8601-0.1.13-py3.6.egg (from m3u8~=0.7.0->locast2dvr) (0.1.13)
Requirement already satisfied: setuptools in /home/steve/.local/lib/python3.6/site-packages (from Paste~=3.5.0->locast2dvr) (51.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests~=2.24.0->locast2dvr) (2018.1.18)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests~=2.24.0->locast2dvr) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests~=2.24.0->locast2dvr) (2.6)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests~=2.24.0->locast2dvr) (1.22)



NOT SURE WHETHER IT'S FULLY INSTALLED I ALSO TRIED (probably not necessary):
steve@ubuntu-plex:~/Downloads/locast2dvr-0.4.35$ sudo python3 -m pip install 'locast2dvr'
WARNING: The directory '/home/steve/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: locast2dvr in /usr/local/lib/python3.6/dist-packages/locast2dvr-0.4.35-py3.6.egg (0.4.35)
Requirement already satisfied: click~=7.1.0 in /usr/local/lib/python3.6/dist-packages/click-7.1.2-py3.6.egg (from locast2dvr) (7.1.2)
Requirement already satisfied: click-config-file~=0.6.0 in /usr/local/lib/python3.6/dist-packages/click_config_file-0.6.0-py3.6.egg (from locast2dvr) (0.6.0)
Requirement already satisfied: click-option-group~=0.5.0 in /usr/local/lib/python3.6/dist-packages/click_option_group-0.5.2-py3.6.egg (from locast2dvr) (0.5.2)
Requirement already satisfied: Flask~=1.1.0 in /usr/local/lib/python3.6/dist-packages/Flask-1.1.2-py3.6.egg (from locast2dvr) (1.1.2)
Requirement already satisfied: fuzzywuzzy~=0.18.0 in /usr/local/lib/python3.6/dist-packages/fuzzywuzzy-0.18.0-py3.6.egg (from locast2dvr) (0.18.0)
Requirement already satisfied: m3u8~=0.7.0 in /usr/local/lib/python3.6/dist-packages/m3u8-0.7.1-py3.6.egg (from locast2dvr) (0.7.1)
Requirement already satisfied: requests~=2.24.0 in /usr/local/lib/python3.6/dist-packages/requests-2.24.0-py3.6.egg (from locast2dvr) (2.24.0)
Requirement already satisfied: waitress~=1.4.0 in /usr/local/lib/python3.6/dist-packages/waitress-1.4.4-py3.6.egg (from locast2dvr) (1.4.4)
Requirement already satisfied: Paste~=3.5.0 in /usr/local/lib/python3.6/dist-packages/Paste-3.5.0-py3.6.egg (from locast2dvr) (3.5.0)
Requirement already satisfied: tabulate~=0.8.0 in /usr/local/lib/python3.6/dist-packages/tabulate-0.8.7-py3.6.egg (from locast2dvr) (0.8.7)
Requirement already satisfied: configobj>=5.0.6 in /usr/local/lib/python3.6/dist-packages/configobj-5.0.6-py3.6.egg (from click-config-file~=0.6.0->locast2dvr) (5.0.6)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from configobj>=5.0.6->click-config-file~=0.6.0->locast2dvr) (1.11.0)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.6/dist-packages/Jinja2-3.0.0a1-py3.6.egg (from Flask~=1.1.0->locast2dvr) (3.0.0a1)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.6/dist-packages/Werkzeug-1.0.1-py3.6.egg (from Flask~=1.1.0->locast2dvr) (1.0.1)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.6/dist-packages/itsdangerous-2.0.0a1-py3.6.egg (from Flask~=1.1.0->locast2dvr) (2.0.0a1)
Requirement already satisfied: MarkupSafe>=1.1 in /usr/local/lib/python3.6/dist-packages/MarkupSafe-2.0.0a1-py3.6-linux-x86_64.egg (from Jinja2>=2.10.1->Flask~=1.1.0->locast2dvr) (2.0.0a1)
Requirement already satisfied: iso8601 in /usr/local/lib/python3.6/dist-packages/iso8601-0.1.13-py3.6.egg (from m3u8~=0.7.0->locast2dvr) (0.1.13)
Requirement already satisfied: setuptools in /home/steve/.local/lib/python3.6/site-packages (from Paste~=3.5.0->locast2dvr) (51.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests~=2.24.0->locast2dvr) (2018.1.18)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests~=2.24.0->locast2dvr) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests~=2.24.0->locast2dvr) (2.6)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests~=2.24.0->locast2dvr) (1.22)


FINALLY:
steve@ubuntu-plex:~/Downloads/locast2dvr-0.4.35$ locast2dvr --config  ~/Downloads/config.ini
2021-01-05 17:19:35 - INFO - CLI: locast2dvr 0.4.35 starting
2021-01-05 17:19:35 - INFO - Facilities: Using cached file: /home/steve/.locast2dvr/facilities.zip
2021-01-05 17:19:35 - INFO - Facilities: Unzipping facilities...
2021-01-05 17:19:37 - INFO - Facilities: Done loading..
2021-01-05 17:19:37 - INFO - LocastService: Logging in with *****@***
2021-01-05 17:19:38 - INFO - LocastService: Locast login successful
2021-01-05 17:19:38 - INFO - LocastService: Loading stations for Denver (cache: True, cache timeout: 3600, days: 8)
2021-01-05 17:19:42 - INFO - DVR: DVR(city: Denver, zip: None, dma: 751, uid: LOCAST2DVR_0, url: http://192.168.1.10:6078) created
2021-01-05 17:19:42 - INFO - Main: Using ffmpeg at /snap/bin/ffmpeg
2021-01-05 17:19:42 - INFO - SSDPServer: Registering upnp:rootdevice (http://192.168.1.10:6078/device.xml)
2021-01-05 17:19:42 - INFO - DVR: DVR(city: Denver, zip: None, dma: 751, uid: LOCAST2DVR_0, url: http://192.168.1.10:6078) HTTP interface started
2021-01-05 17:19:42 - INFO - Main: DVRs:
2021-01-05 17:19:42 - INFO - Main:   City    Zipcode      DMA  UID           URL
2021-01-05 17:19:42 - INFO - Main:   ------  ---------  -----  ------------  ------------------------
2021-01-05 17:19:42 - INFO - Main:   Denver               751  LOCAST2DVR_0  http://192.168.1.10:6078
2021-01-05 17:19:42 - ERROR - locast2dvr.http.interface: Exception on /device.xml [GET]

**Comment by wouterdebie** [comment]
First of all, what version of python do you have?

Could you try the following?

```
$ cd ~/Downloads
$ mkdir locast
$ cd locast
$ python3 -m venv venv 
$ . ./venv/bin/activate
$ pip install locast2dvr
$ locast2dvr --config ~/Downloads/config.ini
```

**Comment by SJLBoulder** [comment]
steve@ubuntu-plex:/usr/local/lib$ ls
python2.7  python3.6  python3.8  python3.9
steve@ubuntu-plex:/usr/local/lib$ find -name 'device.xml'
steve@ubuntu-plex:/usr/local/lib$ 

steve@ubuntu-plex:/usr/local/lib$ cd ~/Down*
steve@ubuntu-plex:~/Downloads$ mkdir locast
steve@ubuntu-plex:~/Downloads$ cd locast
steve@ubuntu-plex:~/Downloads/locast$ python3 -m venv venv
steve@ubuntu-plex:~/Downloads/locast$ . ./venv/bin/activate
(venv) steve@ubuntu-plex:~/Downloads/locast$ pip install locast2dvr
Collecting locast2dvr
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement locast2dvr (from versions: )
No matching distribution found for locast2dvr
(venv) steve@ubuntu-plex:~/Downloads/locast$

**Comment by SJLBoulder** [comment]
(venv) steve@ubuntu-plex:~/Downloads/locast$ python3 --version
Python 3.6.9

**Comment by wouterdebie** [comment]
Ah! locast2dvr requires python > 3.7. That's why a `pip install` doesn't work. I'm not sure if I actually use things that really require >3.7, but since the project doesn't have any unit tests, it's hard to say. Do you have the ability to upgrade to > 3.7?

**Comment by SJLBoulder** [comment]
I'll figure it out.  Sorry I didn't see that requirement, and realize that was the problem.  Thanks.

**Comment by wouterdebie** [comment]
My bad. I hadn't written it down anywhere, but I'v added it to the README. Let me know how it goes.

**Comment by SJLBoulder** [comment]
Success.  Running locast2dvr in a Python3.9 venv with an IP address other than 127.0.0.1 is successful (no 'Exception on /device.xml' error).  

I have more experimenting and reading to do and my terminology may not be accurate:
I installed a Python3.9 venv at ~/py39, and edited .bashrc (for the first time) adding near the begnining:   
"source ~/py39/bin/activate ~/py39"
When I start a new terminal, I'm in a python3.9 environment. 
With that, I was able to run the commands you provided.  Those commands installed and started locast2dvr on IP address/port 192.168.0.10:6078.

Thanks.
